# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f44439854d4a7c4c7e1693b13abe1460"
application_url = "https://edna-puce.vercel.app"
embedded = true
name = "Edna"
handle = "edna-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_customers,write_products"

[auth]
redirect_urls = [
  "https://edna-puce.vercel.app/auth/callback",
  "https://edna-puce.vercel.app/auth/shopify/callback",
  "https://edna-puce.vercel.app/api/auth/callback"
]

[pos]
embedded = false
